### ISSUE TITLE
X-Frame-Options DENY in config/le/ssl.conf causes blank pages (e.g. settings)

### ISSUE THREAD

**Issue by netivajak** [elmerfdz/OrganizrInstaller#234]
Changing config/le/ssl.conf line 19 from 

add_header X-Frame-Options DENY; 

to

config/le/ssl.conf:add_header X-Frame-Options SAMEORIGIN;

Fixes this

Tested on Ubuntu 16.04, Chrome browser.

Hope this helps!

edit: https://github.com/causefx/Organizr/issues/400 is similar.

**Comment by elmerfdz** [comment]
Good spot that, forgot about it, thanks!
