### ISSUE TITLE
[Question] Nginx Configs

### ISSUE THREAD

**Issue by justinglock40** [elmerfdz/OrganizrInstaller#238]
Do you think you could make configs for reverse proxying netdata, portainer, webmin, and cloudcmd? Or help me do it myself. I tried editing some of the ones you have premade that i don't use like transmission and it was an epic fail.

**Comment by elmerfdz** [comment]
I would like to see the changes you've done to the Portainer config, also there are 2 different nginx site templates that OrganizrInstaller uses LE or CF templates.

Think you might need to remove this bit 
```
upstream portainer-upstream {
        server 192.168.1.103:9000;
	keepalive 64;
}

```


and place it outside the main server block
i.e. above line 4
![image](https://user-images.githubusercontent.com/22656503/48985722-a8dbb600-f102-11e8-83fe-f32d9f4c21e7.png)

**Comment by justinglock40** [comment]
Got it working had to remove upstream block and redirect proxy-pass to server IP.

I do have one other question for you. Whats the difference between the CF and LE installations? What changes?

**Comment by elmerfdz** [comment]
Nothing major, it depends on whether you have or are planing to use SSL on your site and how you're planning to do that. If you already have your site on Cloudflare and you want to use Cloudflare SSL then   CF template makes sense but if you're planning to use Let's Encrypt SSL certs then use LE template.

The LE template supports both CF and LE SSL, it just makes things easier to generate LE SSL certs using the installer or if you want to manually do that.
If you want to use LE certs using the CF template, you might have to do some changes to your config depending on the site validation method (http-01 or DNS validation) you choose. 

I would go with the LE template.
