### ISSUE TITLE
wget is not included in centos 7 minimal by default

### ISSUE THREAD

**Issue by Warpedflash** [elmerfdz/OrganizrInstaller#239]
wget is not included in centos 7 minimal by default this causes the wgets to fail when grabbing the organizr content.
Either yum install it as a dependency like you do other requirements or look to use curl to grab the content

**Comment by elmerfdz** [comment]
I've added it to the script and readme. If you test it again, please let me know.

Thanks

**Comment by Warpedflash** [comment]
Looks good to me. Thanks!
