### ISSUE TITLE
Cloudflare CDN

### ISSUE THREAD

**Issue by justinglock40** [elmerfdz/OrganizrInstaller#243]
Anyway to build in a setting creating a configuration for Plex to use Cloudflare as a CDN?

So that it’s Plex.domain.com rather that domain.com/plex

**Comment by christronyxyocum** [comment]
I would strongly suggest you do NOT do that as it will get you banned by CF. @elmerfdz @HalianElf should probably close this out.

**Comment by justinglock40** [comment]
I'm doing it now. It's fine.
