### ISSUE TITLE
Trying to install but Organizr doesn't open.

### ISSUE THREAD

**Issue by rickytin** [elmerfdz/OrganizrInstaller#249]
Trying to install but Organizr doesn't open.
I know it most be something I am doing wrong.
First question:
* "# Do you want to create a SSL enabled site? This option will generate LE SSL certs [y/n]"
I press yes and then it ask
"# Enter your domain name"
This is a specific domain that I pay or I can write whatever I want.
Second question:
2) * "In order to save and reload Nginx configuration, you need to run the NGINX service as the administrator
Username: ricky
Enter Password: "
This password is the one I use as administrator or it's a new password I have to create.
Problem:
PHP: STOP: The service has not been started.
PHP: START: The service did not start due to a logon failure.
NGINX: STOP: The service has not been started.
NGINX: START: The service did not start due to a logon failure.
Why is not starting PHP and NGINX? 

Thanks for the help.

**Comment by elmerfdz** [comment]
Solved: [Link](https://www.reddit.com/r/organizr/comments/aq0t6t/trying_to_install_but_organizr_doesnt_open/)
