### ISSUE TITLE
Windows - Let's Encrypt Failing because NGINX won't start

### ISSUE THREAD

**Issue by aaronjthorpe** [elmerfdz/OrganizrInstaller#263]
When I'm running the install on Windows, NGINX is failing to start after modifying the configs:

`####################################
Updating Nginx and PHP config
####################################

        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
nginx: [emerg] no "ssl_certificate" is defined for the "listen ... ssl" directive in c:\nginx/conf/nginx.conf:25
PHP: STOP: The operation completed successfully.
PHP: START: The operation completed successfully.
NGINX: STOP: The operation completed successfully.
NGINX: Unexpected status SERVICE_PAUSED in response to START control.`

So, when it gets to try and do the SSL cert it fails because it can't verify the domain (I have substituted my actual domain name in the below paste)

`#########################################
WIN-ACME: Genertating LE SSL Certificates
#########################################

 [INFO] A Simple ACME Client for Windows (WACS)
 [INFO] Software version 1912.1.6872.39942 (RELEASE)
 [INFO] IIS not detected
 [INFO] ACME server https://acme-v01.api.letsencrypt.org/
 [INFO] Please report issues at https://github.com/PKISharp/win-acme

 [INFO] Running in Unattended mode
 [INFO] Plugin Manual generated target [Manual] [1 binding - equinox83.com]
 [INFO] Authorize identifier: equinox83.com
 [INFO] Authorizing equinox83.com using http-01 validation (FileSystem)
 [INFO] Answer should now be browsable at http://domainname.com/.well-known/acme-challenge/C1JzPzCH8-yHse5JkVv80vXEwQgbOGpby2irwV-AJw0
 [EROR] Authorization result: invalid
 [EROR] ACME server reported:
 [EROR] [type] urn:acme:error:connection
 [EROR] [detail] Fetching http://domainname.com/.well-known/acme-challenge/C1JzPzCH8-yHse5JkVv80vXEwQgbOGpby2irwV-AJw0: Timeout during connect (likely firewall problem)
 [EROR] [status] 400
 [EROR] Create certificate failed

nginx: [emerg] BIO_new_file("C:\ProgramData\win-acme\httpsacme-v01.api.letsencrypt.org\domainname.com-chain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('C:\ProgramData\win-acme\httpsacme-v01.api.letsencrypt.org\domainname.com-chain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
PHP: STOP: The operation completed successfully.
PHP: START: The operation completed successfully.
NGINX: STOP: The operation completed successfully.
NGINX: Unexpected status SERVICE_PAUSED in response to START control.

Waiting for 0 seconds, press CTRL+C to quit ...
Nginx status : SERVICE_PAUSED
PHP   status : SERVICE_RUNNING
`

**Comment by HalianElf** [comment]
This should be fixed in the new version of the OWI script.
