### ISSUE TITLE
403 Forbidden after install on Ubuntu 18.04

### ISSUE THREAD

**Issue by MatthK** [elmerfdz/OrganizrInstaller#293]
I just installed this on a pristine Ubuntu 18.04 server and it went all smooth up until the Letsencrypt cert.
This one failed with a "not authorized" error message.
After exiting the installer and trying to access the web-interface I just get a "403 Forbidden" message.
The directory /var/www/my.domain.com/ has the owner "www-data", so I would assume it should be fine.
When I try http://my.domain.com/html/index.php I am asked to download the file instead of getting the page displayed.
How can I fix that?

**Comment by elmerfdz** [comment]
Did you capture any screenshots by any chance? Also are you saying it failed during the generation of LE certs?

**Comment by MatthK** [comment]
Yes, the generation of the LE certs failed. Everything before that worked fine, but when it tried to validate the ACME challenge, it came back with the not authorized message.
After that, I only get the 403 Forbidden message.
I have uninstalled it now, but if you need screenshots, I can give it another try. Any specific screenshots I should take?

**Comment by elmerfdz** [comment]
I tried installing on a fresh Ubuntu 18.04 install, I didn't come across any "403 forbidden" errors but did find another issue related to certs, which I fixed. 

Could you please try installing again? first select option 5 > Select 2 (to update the installer to the dev branch) and then use option 4 (Organizr Full Install [Nginx/PHP/Organizr/LE SSL] ).

I'm assuming you did go with option 4 before as well? Please note down the options you choose starting from the certificate specific questions and capture any screenshots of any errors.

**Comment by MatthK** [comment]
It seems the problem is coming (at least partially, but probably all) from the reverse proxy that I have in place. I'm trying to fix this first before I continue trying to install Organizr.
And thank you very much for your help.

**Comment by MatthK** [comment]
After having changed the Reverse Proxy it installed all like a charm and without problems.

**Comment by elmerfdz** [comment]
Great! glad you got it sorted.
