### ISSUE TITLE
Wrong log on details used when creating NGINX and PHP services

### ISSUE THREAD

**Issue by QuasimodoNZ** [elmerfdz/OrganizrInstaller#297]
Specifically the username when the account is a linked as a Microsoft account (rather than a local account).

**Issue:** If the windows user is linked as a Microsoft account the account needs to be their account email and not the account username.

By default it is their name or a version thereof, as represented in the C:\Users\ directory. (for me it was "John Smith", other windows machines I have noticed it was "smitjohn" etc.)

But it needs to be their email address used for the Microsoft account. For example the attached screenshot. (Note the ".\\" prefix is mandatory or it will try and use network domains)
![image](https://user-images.githubusercontent.com/5070396/77814055-84d31f00-7112-11ea-987a-edc0f570b2c8.png)

**Workaround:** Open up services.msc find the service and change the username. This needs to be done quickly before the SSL Certificate step as that step is dependent on the NGINX step.

**Solution:** Automatically figure out if the account is a linked Microsoft account and use the email address. I don't how or if this is possible though.
A prompt for the user as to whether it is a linked account and/or what the username should be.

**Comment by elmerfdz** [comment]
Hmm I've been using a MS account on my Win10 machines since day one, for me it has always been the first 5 letters of my email, even under C:\Users\ and the output of %USERNAME% env var. I know it's the same for other people I know as well.

I've definitely seen your case as well and it's not common. Can't replicate to look into an automatic solution but maybe I can add a manual override option for username.

**Comment by elmerfdz** [comment]
I've tested this and it works fine, could you please test and let me know if it works as expected for you?

**Comment by QuasimodoNZ** [comment]
Yes I believe that works!

As for the differences, I think it may be to do with when the account is set up.
Like from a clean install whether the user account was created from a MS account or was the option skipped and then linked to later. It could even be different for OEM installs but I don't actually know enough about Windows.

**Comment by elmerfdz** [comment]
Thanks for raising this issue and testing 😀
